# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Working/OndeviceAI2/Basys-3-Master.xdc

# Block Designs: bd/stopwatch_design/stopwatch_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design || ORIG_REF_NAME==stopwatch_design} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_microblaze_0_0/stopwatch_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_microblaze_0_0 || ORIG_REF_NAME==stopwatch_design_microblaze_0_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_dlmb_v10_0/stopwatch_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_dlmb_v10_0 || ORIG_REF_NAME==stopwatch_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_ilmb_v10_0/stopwatch_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_ilmb_v10_0 || ORIG_REF_NAME==stopwatch_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_dlmb_bram_if_cntlr_0/stopwatch_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==stopwatch_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_ilmb_bram_if_cntlr_0/stopwatch_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==stopwatch_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_lmb_bram_0/stopwatch_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_lmb_bram_0 || ORIG_REF_NAME==stopwatch_design_lmb_bram_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_mdm_1_0/stopwatch_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_mdm_1_0 || ORIG_REF_NAME==stopwatch_design_mdm_1_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_clk_wiz_1_0/stopwatch_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_clk_wiz_1_0 || ORIG_REF_NAME==stopwatch_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_rst_clk_wiz_1_100M_0/stopwatch_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_axi_uartlite_0_0/stopwatch_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_axi_uartlite_0_0 || ORIG_REF_NAME==stopwatch_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_xbar_0/stopwatch_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_xbar_0 || ORIG_REF_NAME==stopwatch_design_xbar_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_microblaze_0_axi_periph_0/stopwatch_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==stopwatch_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_gpio_0_0/stopwatch_design_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_gpio_0_0 || ORIG_REF_NAME==stopwatch_design_gpio_0_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_gpio_1_0/stopwatch_design_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_gpio_1_0 || ORIG_REF_NAME==stopwatch_design_gpio_1_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_gpio_2_0/stopwatch_design_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_gpio_2_0 || ORIG_REF_NAME==stopwatch_design_gpio_2_0} -quiet] -quiet

# IP: bd/stopwatch_design/ip/stopwatch_design_gpio_3_0/stopwatch_design_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stopwatch_design_gpio_3_0 || ORIG_REF_NAME==stopwatch_design_gpio_3_0} -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_microblaze_0_0/stopwatch_design_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_microblaze_0_0 || ORIG_REF_NAME==stopwatch_design_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_microblaze_0_0/stopwatch_design_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_dlmb_v10_0/stopwatch_design_dlmb_v10_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_ilmb_v10_0/stopwatch_design_ilmb_v10_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_dlmb_bram_if_cntlr_0/stopwatch_design_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_ilmb_bram_if_cntlr_0/stopwatch_design_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_lmb_bram_0/stopwatch_design_lmb_bram_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_mdm_1_0/stopwatch_design_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_mdm_1_0 || ORIG_REF_NAME==stopwatch_design_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_mdm_1_0/stopwatch_design_mdm_1_0_ooc_trace.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_clk_wiz_1_0/stopwatch_design_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_clk_wiz_1_0 || ORIG_REF_NAME==stopwatch_design_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_clk_wiz_1_0/stopwatch_design_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_clk_wiz_1_0 || ORIG_REF_NAME==stopwatch_design_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_clk_wiz_1_0/stopwatch_design_clk_wiz_1_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_rst_clk_wiz_1_100M_0/stopwatch_design_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_rst_clk_wiz_1_100M_0/stopwatch_design_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==stopwatch_design_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_axi_uartlite_0_0/stopwatch_design_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_axi_uartlite_0_0 || ORIG_REF_NAME==stopwatch_design_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_axi_uartlite_0_0/stopwatch_design_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_axi_uartlite_0_0/stopwatch_design_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==stopwatch_design_axi_uartlite_0_0 || ORIG_REF_NAME==stopwatch_design_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/ip/stopwatch_design_xbar_0/stopwatch_design_xbar_0_ooc.xdc

# XDC: c:/Working/OndeviceAI2/260623_microblaze_gpio/260623_microblaze_gpio.gen/sources_1/bd/stopwatch_design/stopwatch_design_ooc.xdc
